name: Feature request
description: Propose a capability
labels: ['type:feature']
body:
  - type: textarea
    id: problem
    attributes:
      label: The problem
      description: What reconciliation problem are you unable to solve today?
    validations: { required: true }
  - type: textarea
    id: proposal
    attributes:
      label: Proposed solution
  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives considered
